### PR TITLE
feat: add OutdoorTemperature and Setpoint endtime

### PR DESCRIPTION
**Pull request by fhempy**
- Add OutdoorTemperature
 - Add Setpoint endtime
 - some code style fixes

### CODE REVIEW

**Comment by dominikkarall** [comment]
@MislavMandaric can you please check this PR and if ok publish a new release? Thx!

**Comment by dominikkarall** [comment]
@MislavMandaric do you plan to continue the work on this library? If so, it would be great if you could merge this PR.

**Comment by MislavMandaric** [comment]
Hey @dominikkarall.

Thank you for your contribution 👍 

I don't currently have contribution guidelines documented (I probably should do that 😅 ) but can you please make the following changes to your PR:
1. This library uses [semantic release](https://github.com/semantic-release/semantic-release) to automate versioning and release notes, can you please use it's commit naming guidelines (ie. each commit should have the structure of `feat: Message` or `fix: Message`).
2. This PR adds two separate features (outdoor temperature and setpoint endtime), so these should be two separate PRs
3. Each new feature or bugfix PR should start by opening an issue first, which is where we can discuss about those changes

Don't worry about the third point for these changes, but can you please do the first two? And sorry for the delay, working on this wasn't my priority for the last couple of months.

**Comment by MislavMandaric** [comment]
Hey @fhempy. Any chance you had time to look at my comment above? I have some time to look at your contributions and would like to merge them as its clearly something that improves the library for everyone 👍

**Comment by MislavMandaric** [comment]
Hey @fhempy.

I'll merge this but because commits are not named properly, I'll create a new PR with some small changes I wanted to comment on this PR once the previous comments are resolved.

Thank you for this contribution, I really appreciate it. ❤️

**Comment by fhempy** [comment]
Sorry, I completely forgot this one. Thanks for your update!

**Pull request merged**
